package com.example.directpin.model

enum class CodeResult(val code: Int, val message: String) {
    OK(0, "Operação bem sucedida"),
    ALREADY_OPEN(1, "Conexão já aberta"),
    INVALID_CALL(2, "Chamada inválida"),
    INVALID_PARAMETER(3, "Parâmetro inválido"),
    TIMEOUT(4, "Tempo esgotado"),
    CANCELED_OPERATION(5, "Operação cancelada"),
    UNINITIALIZED_PINPAD(6, "Pinpad não inicializado"),
    INVALID_MODEL(7, "Modelo inválido"),
    UNSUPPORTED_OPERATION(8, "Operação não suportada"),
    EXPIRED_TABLES(9, "Tabelas expiradas"),
    TABLE_WRITE_ERROR(10, "Erro de escrita na tabela"),
    MAG_CARD_READ_ERROR(11, "Erro de leitura do cartão magnético"),
    MISSING_PIN_KEY(12, "Chave PIN ausente"),
    MISSING_CARD(13, "Cartão ausente"),
    BUSY_PINPAD(14, "Pinpad ocupado"),
    SAM_MODULE_ERROR(15, "Erro do módulo SAM"),
    MISSING_SAM(16, "SAM ausente"),
    INVALID_SAM(17, "SAM inválido"),
    MUTE_CARD(18, "Cartão mudo"),
    CARD_COMMUNICATION_ERROR(19, "Erro de comunicação do cartão"),
    INVALIDATED_CARD(20, "Cartão invalidado"),
    PROBLEMATIC_CARD(21, "Cartão problemático"),
    CARD_WITH_INVALID_DATA(22, "Cartão com dados inválidos"),
    CARD_WITHOUT_APPLICATION(23, "Cartão sem aplicação"),
    UNUSED_APPLICATION(24, "Aplicação não utilizada"),
    FALLBACK_ERROR(25, "Erro de fallback"),
    INVALID_VALUE(26, "Valor inválido"),
    EXCEEDS_AID_CAPACITY(27, "Excede a capacidade do AID"),
    BLOCKED_CARD(28, "Cartão bloqueado"),
    MULTIPLE_CTLSS(29, "Mais de um cartão apresentado"),
    CTLSS_COMMUNICATION_ERROR(30, "Erro de comunicação com o cartão"),
    INVALIDATED_CTLSS(31, "Cartão invalidado, use chip/tarja"),
    PROBLEMATIC_CTLSS(32, "Cartão inválido, use chip/tarja"),
    CTLSS_WITHOUT_APPLICATION(33, "Modo inválido, use chip/tarja"),
    UNSUPPORTED_CTLSS_APPLICATION(34, "Não aceito, use chip/tarja"),
    EXTERNAL_CTLSS_DEVICE(35, "Verifique o dispositivo"),
    CTLSS_CHANGE_INTERFACE(36, "Use chip ou tarja"),
    INTERNAL_ERROR(37, "Erro interno"),
    ABORTED_OPERATION(38, "Operação abortada"),
    CARD_CHIP(39, "Cartão com chip"),
    PRODUCT_EMPTY(40, "Lista de produtos vazia"),
    DIVERT_CARD_NUMBER(41, "Número de cartão divergente"),
    REJECTED_TRANSACTION(42, "Transação rejeitada"),
    CARD_REJECTED(43, "Transação rejeitada pelo cartão"),
    INVALID_TRANSACTION(44, "Transação inválida"),
    PRINT_ERROR(45, "Falha na impressão, verifique a impressora"),
    EMPTY_TRANSACTION(46, "Transação não encontrada"),
    CARD_NUMBER_INVALID(47, "Número de cartão inválido"),
    INVALID_EXP_DATE(48, "Data de expiração inválida"),
    NONE_PRODUCTS(49, "Nenhum produto encontrado"),
    NO_CREDIT_INSTALLMENT_SELECTED(50, "Nenhum modo de parcelamento configurado"),
    LOGON_NOT_PERFORMED(51, "O Logon não foi realizado antes do fluxo selecionado"),
    RESET_CONFIGURATION(52, "Informações divergentes, resete o seu terminal"),
    MIN_INSTALLMENT_AMOUNT(53, "Valor por parcela abaixo do permitido"),
    MAX_INSTALLMENT_AMOUNT(54, "Valor por parcela acima do permitido"),
    MAX_INSTALLMENT(55, "Quantidade de parcelas acima do permitido");

    companion object {
        fun fromCode(code: Int): CodeResult? = entries.find { it.code == code }
    }
}

